# Generated by Django 4.1.6 on 2023-02-06 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('word', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='word.category'),
        ),
        migrations.AlterField(
            model_name='extraimage',
            name='extratext',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraimage', to='word.extratext'),
        ),
        migrations.AlterField(
            model_name='extratext',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extratext', to='word.article'),
        ),
    ]
