# Generated by Django 4.1.6 on 2023-02-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='position',
        ),
    ]
